-- SYNTHETIC DEMONSTRATION DATA ONLY. Not official or operational Lucena City data.
insert into public.barangays(id,psgc_code,barangay_name,population,source,reference_year,is_demo) values
('10000000-0000-4000-8000-000000000001','DEMO-045624001','Dalahican',12000,'Project AGAP synthetic demonstration dataset',2026,true),
('10000000-0000-4000-8000-000000000002','DEMO-045624002','Cotta',9000,'Project AGAP synthetic demonstration dataset',2026,true),
('10000000-0000-4000-8000-000000000003','DEMO-045624003','Barra',7000,'Project AGAP synthetic demonstration dataset',2026,true),
('10000000-0000-4000-8000-000000000004','DEMO-045624004','Gulang-gulang',15000,'Project AGAP synthetic demonstration dataset',2026,true),
('10000000-0000-4000-8000-000000000005','DEMO-045624005','Ibabang Dupay',11000,'Project AGAP synthetic demonstration dataset',2026,true)
on conflict(psgc_code) do nothing;
insert into public.population_profiles(barangay_id,population,households,average_household_size,children,older_persons,persons_with_disabilities,source,reference_year,is_demo)
select id,population,round(population/4.2),4.2,round(population*.28),round(population*.08),round(population*.04),'Project AGAP synthetic demonstration dataset',2026,true from public.barangays where is_demo on conflict do nothing;
insert into public.hazards(id,name,hazard_type,source,is_demo) values ('20000000-0000-4000-8000-000000000001','Synthetic Severe Rainfall Scenario','FLOOD','Project AGAP synthetic demonstration dataset',true) on conflict do nothing;
insert into public.methodologies(id,name,description,source,version,likelihood_scale,severity_scale,parameters,active_status) values
('30000000-0000-4000-8000-000000000001','AGAP 5x5 Demonstration Matrix','Risk equals likelihood multiplied by severity. Replace with an LGU-approved methodology before operational use.','Project AGAP synthetic demonstration methodology','demo-1.0','{"min":1,"max":5}','{"min":1,"max":5}','{"categories":[{"min":1,"max":4,"label":"LOW"},{"min":5,"max":9,"label":"MODERATE"},{"min":10,"max":16,"label":"HIGH"},{"min":17,"max":25,"label":"VERY_HIGH"}]}',true)
on conflict(name,version) do nothing;
insert into public.advisories(id,source_agency,advisory_type,bulletin_reference,warning_information,issue_time,validity_start,validity_end,affected_areas,source_link,verification_status,is_demo)
values ('40000000-0000-4000-8000-000000000001','SYNTHETIC — Project AGAP Demo','Severe Rainfall Demonstration','DEMO-BULLETIN-001','Synthetic heavy-rainfall scenario for software demonstration only.',now(),now()-interval '1 hour',now()+interval '365 days',array['Dalahican','Cotta','Barra'],'https://example.invalid/agap-demo','VERIFIED',true)
on conflict(source_agency,bulletin_reference) do update set validity_end=excluded.validity_end;
insert into public.preparedness_capacities(barangay_id,evacuation_capacity,temporary_shelter_capacity,responders,equipment,backup_power,communication_access,facility_status,validation_date,source,limitations,is_demo)
select id,800,200,20,'{"vehicles":2,"radios":8}','UNVERIFIED',array['SMS','Radio','Barangay Announcements'],'FOR_REVIEW',current_date,'Project AGAP synthetic demonstration dataset',array['Synthetic capacities require replacement and LGU validation.'],true from public.barangays where is_demo and not exists(select 1 from public.preparedness_capacities p where p.barangay_id=barangays.id);
insert into public.population_exposure_estimates(barangay_id,hazard_id,estimated_exposed_population,estimated_households,vulnerable_group_estimates,estimation_method,confidence_level,source,reference_date,limitations,is_demo)
select b.id,'20000000-0000-4000-8000-000000000001',round(b.population*.35),round(b.population*.35/4.2),'{"children":980,"older_persons":280,"persons_with_disabilities":140}','INHABITED_AREA_PROPORTION_FALLBACK','LOW','Project AGAP synthetic demonstration estimate',current_date,array['Pre-disaster estimate only; not affected population and not household-level exposure.'],true from public.barangays b where b.is_demo and not exists(select 1 from public.population_exposure_estimates e where e.barangay_id=b.id);
insert into public.critical_facilities(name,type,barangay_id,operational_status,capacity,source,is_demo)
select 'Synthetic '+barangay_name+' Evacuation Facility','EVACUATION_CENTER',id,'UNVERIFIED',500,'Project AGAP synthetic demonstration dataset',true from public.barangays b where b.is_demo and not exists(select 1 from public.critical_facilities f where f.barangay_id=b.id);
insert into public.household_profiles(household_code,barangay_id,optional_purok,household_members,has_children,has_older_person,has_pwd_or_mobility_limitation,needs_essential_medicine,has_pets,housing_characteristics,communication_methods,is_demo)
values ('DLH-P03-HH0048','10000000-0000-4000-8000-000000000001','Purok 3',5,true,true,false,true,true,'{"type":"synthetic demo profile"}',array['SMS','Radio'],true) on conflict(household_code) do nothing;
insert into public.action_rules(rule_id,disaster_phase,hazard_or_condition,fact_field,operator,threshold,approved_action,why_it_applies,source_agency,source_document,target_audience,responsible_unit,requires_lgu_confirmation,version,active_status) values
('DEMO-LGU-001','PRE_DISASTER','High risk','riskCategory','IN','["HIGH","VERY_HIGH"]','Flag the assessment for priority LGU review.','The deterministic risk category meets the review threshold.','SYNTHETIC — Project AGAP','Demonstration action-rule register','LGU','CDRRMO Review Team',true,'demo-1.0',true),
('DEMO-LGU-002','PRE_DISASTER','Capacity gap','capacityGap','GT','0','Request validation of shelter and evacuation capacity.','Estimated potential exposure exceeds recorded validated planning capacity.','SYNTHETIC — Project AGAP','Demonstration action-rule register','LGU','Evacuation and Camp Management',true,'demo-1.0',true),
('DEMO-HH-001','HOUSEHOLD','Children present','hasInfantOrChild','TRUTHY','true','Prepare child-specific food, clothing, identification, and comfort items.','The quick profile indicates an infant or child in the household.','SYNTHETIC — Project AGAP','Demonstration household-rule register','HOUSEHOLD','Household',false,'demo-1.0',true),
('DEMO-HH-002','HOUSEHOLD','Older person present','hasOlderPerson','TRUTHY','true','Prepare medicines, mobility support, and a caregiver contact plan.','The quick profile indicates an older household member.','SYNTHETIC — Project AGAP','Demonstration household-rule register','HOUSEHOLD','Household',false,'demo-1.0',true),
('DEMO-HH-003','HOUSEHOLD','Medicine need','hasEssentialMedicineNeed','TRUTHY','true','Prepare an appropriate personal medicine supply and prescription information.','The quick profile records an essential medicine need.','SYNTHETIC — Project AGAP','Demonstration household-rule register','HOUSEHOLD','Household',false,'demo-1.0',true),
('DEMO-HH-004','HOUSEHOLD','Pets present','hasPets','TRUTHY','true','Prepare pet food, water, identification, and a safe carrier or restraint.','The quick profile indicates pets.','SYNTHETIC — Project AGAP','Demonstration household-rule register','HOUSEHOLD','Household',false,'demo-1.0',true),
('DEMO-POST-001','POST_IMMEDIATE','Reports await validation','populationAwaitingValidation','GT','0','Validate reported affected households and persons.','Reported totals exceed validated totals.','SYNTHETIC — Project AGAP','Demonstration post-impact rule register','LGU','Assessment and Validation Team',true,'demo-1.0',true),
('DEMO-POST-002','POST_STABILIZATION','Service disruption','hasServiceDisruption','TRUTHY','true','Track and validate restoration of essential services.','A service disruption is recorded in field evidence.','SYNTHETIC — Project AGAP','Demonstration post-impact rule register','LGU','Public Services Coordination',true,'demo-1.0',true),
('DEMO-POST-003','POST_MITIGATION','Recurring access constraint','hasAccessibilityConstraints','TRUTHY','true','Review recurring access constraints and update preparedness records.','Validated access constraints should inform mitigation review.','SYNTHETIC — Project AGAP','Demonstration post-impact rule register','LGU','Planning and Engineering Review',true,'demo-1.0',true)
on conflict(rule_id,version) do nothing;

insert into public.action_rules(rule_id,disaster_phase,hazard_or_condition,fact_field,operator,threshold,approved_action,why_it_applies,source_agency,source_document,target_audience,responsible_unit,requires_lgu_confirmation,version,active_status) values
('DEMO-HH-005','HOUSEHOLD','Generic barangay guidance','genericBarangay','TRUTHY','true','Monitor verified official advisories and prepare household essentials appropriate to your needs.','A generic barangay card provides only approved general preparedness guidance.','SYNTHETIC — Project AGAP','Demonstration household-rule register','HOUSEHOLD','Household',false,'demo-1.0',true),
('DEMO-POST-001','POST_IMMEDIATE','Incomplete validation','validationIncomplete','TRUTHY','true','Validate reported affected households and persons.','Reported figures remain distinct from validated figures.','SYNTHETIC — Project AGAP','Demonstration post-impact rule register','LGU','Validation Team',true,'demo-1.0',true),
('DEMO-POST-002','POST_STABILIZATION','Service disruption','serviceDisruption','TRUTHY','true','Validate and track restoration of essential services.','A service disruption was reported and requires confirmation and monitoring.','SYNTHETIC — Project AGAP','Demonstration post-impact rule register','LGU','Utilities Coordination Unit',true,'demo-1.0',true),
('DEMO-POST-003','POST_IMMEDIATE','Water need awaiting validation','waterNeedValidated','TRUTHY','true','Confirm potable water requirements before augmentation planning.','A water need was recorded and must be validated before quantities or allocation decisions.','SYNTHETIC — Project AGAP','Demonstration post-impact rule register','LGU','Health and WASH Unit',true,'demo-1.0',true)
on conflict(rule_id,version) do nothing;

insert into public.risk_assessments(id,barangay_id,advisory_id,methodology_id,likelihood,severity,risk_result,risk_category,threat_level,adaptive_capacity,relative_vulnerability,evidence,data_date,confidence_level,limitations)
select gen_random_uuid(),b.id,'40000000-0000-4000-8000-000000000001','30000000-0000-4000-8000-000000000001',3,4,12,'HIGH',3,2,1.5,'["Synthetic demonstration input only"]',current_date,'LOW',array['Replace all values with verified operational evidence.'] from public.barangays b where b.is_demo and not exists(select 1 from public.risk_assessments r where r.barangay_id=b.id);
insert into public.damage_reports(client_id,barangay_id,reported_affected_persons,reported_affected_households,vulnerable_groups,damage_type,severity,critical_facility_condition,access_condition,evidence,source,reported_at,device_timestamp,verification_status,sync_status,is_demo)
select gen_random_uuid(),id,25,6,'{"older_persons":2}','Synthetic flood damage report','UNDETERMINED','UNVERIFIED','UNVERIFIED','[{"type":"note","reference":"Synthetic demo evidence"}]','Project AGAP synthetic demonstration dataset',now(),now(),'UNVERIFIED','SYNCED',true from public.barangays where barangay_name='Dalahican' and not exists(select 1 from public.damage_reports where is_demo);
insert into public.needs_reports(barangay_id,water_need,shelter_need,medicine_need,urgency,source,verification_status,is_demo)
select id,true,true,true,'HIGH','Project AGAP synthetic demonstration dataset','UNVERIFIED',true from public.barangays where barangay_name='Dalahican' and not exists(select 1 from public.needs_reports where is_demo);
insert into public.post_impact_reviews(advisory_id,event_reference,barangay_id,reported_population,validated_population,reported_households,validated_households,vulnerable_groups,damage_summary,facility_condition,service_disruption,accessibility_constraints,urgent_unmet_needs,validation_status,review_state)
select '40000000-0000-4000-8000-000000000001','DEMO-EVENT-001',id,25,0,6,0,'{"reported":"Synthetic demo only"}','Synthetic report awaiting validation','UNVERIFIED','UNVERIFIED','UNVERIFIED','Water, shelter, and medicine reports awaiting validation','UNVERIFIED','OPEN' from public.barangays where barangay_name='Dalahican' and not exists(select 1 from public.post_impact_reviews where event_reference='DEMO-EVENT-001');
