import { assertCurrentAdvisory } from "./advisory";
import { evaluateActionRules, type ActionRule } from "./actionRuleEngine";
import { calculateCapacityGap } from "./capacityEngine";

export function generateLGUActionCard(input: { barangay: string; hazard: string; advisory: Record<string, unknown>; risk: Record<string, unknown>; exposure: any; capacity: any; facilities: any[]; rules: ActionRule[] }) {
  assertCurrentAdvisory(input.advisory as any, input.barangay);
  const gap = calculateCapacityGap({ estimatedExposure: input.exposure.estimatedPopulation, validatedCapacity: input.capacity.evacuationCapacity + input.capacity.temporaryShelterCapacity, confidence: input.exposure.confidenceLevel, evidence: input.capacity.evidence ?? [] });
  const facts = { riskCategory: input.risk.riskCategory, capacityGap: gap.capacityGap, criticalFacilityUnverified: input.facilities.some(f => f.operationalStatus === "UNVERIFIED"), communicationAccess: input.capacity.communicationAccess };
  return { outputType: "LGU_ACTION_CARD", situation: { barangay: input.barangay, hazard: input.hazard, currentVerifiedAdvisory: input.advisory, riskCategory: input.risk.riskCategory, deterministicCalculation: input.risk.calculation, assessmentDate: input.risk.assessmentDate, verificationState: "VERIFIED" }, potentialExposure: input.exposure, preparednessCapacity: { ...input.capacity, ...gap, criticalFacilities: input.facilities }, whyAttentionIsNeeded: { riskInputs: { likelihood: input.risk.likelihood, severity: input.risk.severity }, methodology: input.risk.methodology, relativeVulnerability: input.risk.relativeVulnerability, dataDate: input.risk.dataDate, confidenceLevel: input.risk.confidenceLevel, limitations: input.risk.limitations, riskResult: input.risk.riskResult, exposureEvidence: input.exposure.source, vulnerabilityEvidence: input.risk.evidence, capacityLimitations: input.capacity.limitations ?? [], missingInformation: [] }, recommendedActions: evaluateActionRules(input.rules, facts, "PRE_DISASTER") };
}

export function generateHouseholdCard(input: { barangay: string; householdCode?: string; profile: Record<string, unknown>; advisory: any; rules: ActionRule[]; language: "en" | "fil" }) {
  assertCurrentAdvisory(input.advisory);
  return { outputType: "HOUSEHOLD_ACTION_CARD", barangay: input.barangay, householdCode: input.householdCode ?? null, advisoryTitle: input.advisory.advisoryType, advisoryReference: input.advisory.bulletinReference, advisoryValidity: input.advisory.validityEnd, advisoryVerificationState: "VERIFIED", generatedAt: new Date().toISOString(), lastSyncAt: null, languageLabel: input.language === "fil" ? "Filipino" : "English", actions: evaluateActionRules(input.rules, { genericBarangay:true, ...input.profile }, "HOUSEHOLD").map(a => ({ id: a.actionRuleId, title: input.language === "fil" ? (input.rules.find(r => r.ruleId === a.actionRuleId)?.approvedActionFil ?? a.action) : a.action, explanation: input.language === "fil" ? (input.rules.find(r => r.ruleId === a.actionRuleId)?.whyItAppliesFil ?? a.whyItApplies) : a.whyItApplies, sourceRule: `${a.actionRuleId} (${a.source})` })), limitations: [...(input.advisory.isDemo ? ["SYNTHETIC DEMONSTRATION: not official disaster information."] : []), ...(input.language === "fil" && input.rules.some(r => !r.approvedActionFil) ? ["May mga source-approved actions na nasa English lamang; hindi gumagawa ng hindi aprubadong salin ang AGAP."] : []), "Follow current instructions from authorized disaster officials. AGAP does not issue evacuation orders or declare areas safe."] };
}

export function generatePostImpactActionCard(input: { barangay: string; eventReference: string; facts: Record<string, unknown>; rules: ActionRule[] }) {
  const actions = evaluateActionRules(input.rules, input.facts).filter(a => ["POST_IMMEDIATE", "POST_STABILIZATION", "POST_MITIGATION"].includes(input.rules.find(r => r.ruleId === a.actionRuleId)?.disasterPhase ?? "")).map(a => ({ ...a, phase: ({ POST_IMMEDIATE: "IMMEDIATE", POST_STABILIZATION: "STABILIZATION", POST_MITIGATION: "MITIGATION" } as const)[input.rules.find(r => r.ruleId === a.actionRuleId)!.disasterPhase as "POST_IMMEDIATE" | "POST_STABILIZATION" | "POST_MITIGATION"] }));
  return { outputType: "POST_IMPACT_ACTION_CARD", barangay: input.barangay, eventReference: input.eventReference, generatedAt: new Date().toISOString(), reportedAffectedPersons: input.facts.reportedAffectedPersons ?? 0, validatedAffectedPersons: input.facts.validatedAffectedPersons ?? 0, populationAwaitingValidation: Math.max(0, Number(input.facts.reportedAffectedPersons ?? 0) - Number(input.facts.validatedAffectedPersons ?? 0)), actions };
}
